export const LOAD_DATA_REQUEST = 'LOAD_DATA_REQUEST';
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
export const LOAD_DATA_ERROR = 'LOAD_DATA_ERROR';

export const ADD_CHAT_MESSAGE = 'ADD_CHAT_MESSAGE';
export const ADD_CHAT_MESSAGE_SUCCESS = 'ADD_CHAT_MESSAGE_SUCCESS';

export const END_CHAT_REQUEST = 'END_CHAT_REQUEST';
export const END_CHAT_SUCCESS = 'END_CHAT_SUCCESS';

export const ADD_CHAT_REQUEST = 'ADD_CHAT_REQUEST';
export const HIDE_CHAT_REQUEST = 'HIDE_CHAT_REQUEST';
export const REVEAL_CHAT_REQUEST = 'REVEAL_CHAT_REQUEST';
export const CLOSE_CHAT_REQUEST = 'CLOSE_CHAT_REQUEST';

export const CHAT_SCREEN_LIMIT_ERROR = 'CHAT_SCREEN_LIMIT_ERROR';
